### ISSUE TITLE
Invalid default cron schedule

### ISSUE THREAD

**Issue by PedroPerpetua** [kartoza/docker-pg-backup#108]
### What is the bug or the crash?

The default value for the cron schedule is `0 24 * * *` which is actually invalid and will generate an error at start:
```
"/backup-scripts/backups-cron":1: bad hour
errors in crontab file, can't install.
```

For backups at midnight, the value should be `0 0 * * *`.

The issue can be found in the `start.sh` script, in the following snippet:
```sh
# Lines 152-154
      if [ -z "${CRON_SCHEDULE}" ]; then
        export CRON_SCHEDULE='0 24 * * *'
      fi
```

### Steps to reproduce the issue

Create a simple compose with Postgres and this image; don't change the default cron task schedule.

### Versions

My corresponding images:
```yml
  db:
    image: postgres:17.0-alpine
  backup:
    image: kartoza/pg-backup:17-3.5
```
