### ISSUE TITLE
Cannot change Postgres user name

### ISSUE THREAD

**Issue by kaspernj** [kartoza/docker-pg-backup#21]
I am using Docker compose and have it set up like this:
```
dbbackup:
  image: kartoza/pg-backup:11.0
  hostname: pg-backups
  depends_on:
    - postgres
  volumes:
    - /mybackupspath:/backups
  environment:
    - DUMPPREFIX=myprefix
    - POSTGRES_USER=dev
    - POSTGRES_PASS=mypassword
    - POSTGRES_PORT=5432
    - POSTGRES_HOST=postgres
    - POSTGRES_DBNAME=mydatabasename
```

However if I open a terminal inside the container and execute `cat pgenv.sh` I get this:
```
export PGUSER=docker
export PGPASSWORD=mypassword
export PGPORT=5432
export PGHOST=postgres
export PGDATABASE=mydatabasename
export DUMPPREFIX=myprefix
export ARCHIVE_FILENAME=
```

I expected `export PGUSER=dev` but got `export PGUSER=docker`.

I haven't been able to figure out why this happens unfortunately.
