### ISSUE TITLE
backup to S3 not working

### ISSUE THREAD

**Issue by sushilbansal** [kartoza/docker-pg-backup#59]
Hi, I tried using the S3 bucket; backup container is not running. I tested the AWS credentials and bucket using some other means and bucket is definitely connecting and working.

```
version: '3'
volumes:
  postgres-data:
  pgadmin:
services:
  node-docker:
    container_name: node_container
    build: .
    ports:
      - 3000:4000

  postgres:
    container_name: postgres_container
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: sushilbansal1982@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  dbbackups:
    container_name: dbbackups_container
    image: kartoza/pg-backup:${POSTGRES_MAJOR_VERSION:-14}-${POSTGIS_MAJOR_VERSION:-3}.${POSTGIS_MINOR_RELEASE:-1}
    environment:
      - DUMPPREFIX=backup
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=password
      - POSTGRES_PORT=5432
      - CRON_SCHEDULE="*/5 * * * *"
      - STORAGE_BACKEND="S3"
      - ACCESS_KEY_ID=MY_AWS_KEY_ID
      - SECRET_ACCESS_KEY=MY_AWS_SECRET_KEY
      - DEFAULT_REGION=eu-west-2
      - BUCKET=MY_AWS_BUCKET
      - SSL_SECURE=True
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
```
