### ISSUE TITLE
Backup service unavailable

### ISSUE THREAD

**Issue by freemankevin** [kartoza/docker-pg-backup#67]
Use version：v12.0

```shell
$ docker logs -f --tail 1000 postgis-dbbackups-1
psql: error: could not connect to server: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Start script running with these environment options
DUMPPREFIX=PG_db
PG_ENV=/pgenv.sh
```

**Comment by techpet** [comment]
Any news on this? Having the same problem as @freemankevin reported. 

```
 postgis:
        image: kartoza/postgis:12.4
        container_name: postgis_${ENVIRONMENT}
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASS=${POSTGRES_PASS}
            - POSTGRES_DBNAME=${POSTGRES_DBNAME}
        expose: 
            - 5432
        volumes:
            - "./${POSTGRES_VOLUME}:/var/lib/postgresql"
        healthcheck:
            test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DBNAME}"
dbbackups:
        image: kartoza/pg-backup:12.0
        volumes:
        - ./db-backups:/backups
        env_file:
        - .env
        environment:
        - DUMPPREFIX=PG_gis
        - POSTGRES_HOST=postgis
        - POSTGRES_DBNAME=${POSTGRES_DBNAME}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - POSTGRES_PORT=5432
        #- CRON_SCHEDULE="*/5 * * * *"
        restart: on-failure
        depends_on:
          postgis:
            condition: service_healthy
```
